### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cleberlira** [RESTdesc/RESTdesc-Photo-Example#3]
Node server.js

Attempting to run the example the error below occurs:

Error: Cannot find module 'formidable'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Doutorado\Sistemas Web\Seminário I\RESTdesc-Photo-Example-master\photo-server.js:7:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by RubenVerborgh** [comment]
Disclaimer: this library is no longer maintained.

However: did you run `npm install`?
